name: Android Build

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    # On retire le "working-directory" ici pour tester si le fichier est à la racine
    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Build APK with Gradle
      run: ./gradlew assembleDebug --stacktrace --info

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CraftVerse-Debug-APK
        path: "**/build/outputs/apk/debug/*.apk"
